USE [C:\PROGRAMS\C#\УЧЕБНЫЕ\ASP NET MVC\TESTVS15\TESTVS15\APP_DATA\MYDB.MDF];
CREATE SEQUENCE Seq START WITH 1 INCREMENT BY 1;
CREATE TABLE T1 (col1 CHAR(10), col2 CHAR(10));
INSERT INTO [dbo].[T1](col1, col2)
SELECT NEXT VALUE FOR Seq OVER(ORDER BY dept_name ASC), budget
FROM (
SELECT dept_name, budget
FROM [dbo].[project_dept]
ORDER BY budget, dept_name DESC
OFFSET 0 ROWS FETCH FIRST 5 ROWS ONLY) 
AS D;