/*USE [C:\PROGRAMS\C#\УЧЕБНЫЕ\ASP NET MVC\TESTVS15\TESTVS15\APP_DATA\MYDB.MDF];
CREATE TABLE [dbo].[Table1]
(column1 INT NOT NULL PRIMARY KEY,
column2 CHAR(10));*/
INSERT INTO [dbo].[Table1] VALUES (NEXT VALUE FOR [dbo].[Sequence1], 'A');
INSERT INTO [dbo].[Table1] VALUES (NEXT VALUE FOR [dbo].[Sequence1], 'B');